CREATE USER appusrtest WITH PASSWORD 'c5863446010dc1c0d3c9152b4fb79a0c64d8d58af58001e3f060da2852b40150';

GRANT ALL PRIVILEGES ON DATABASE invex TO appusrtest;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO appusrtest;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO appusrtest;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO appusrtest;
GRANT USAGE ON SCHEMA public TO appusrtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO appusrtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO appusrtest;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO appusrtest;